host: "localhost"
port: "8000"

db: 
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "loyalty_system"
    sslmode: "disable"

    migration:
                isAllowed: true
                
auth:
    #token live(minutes)
    accessTokenExp: 30

